"""
Google Gemini + CIAF Watermarking - Image Watermarking Example

Demonstrates watermarking images generated by AI models (e.g., Gemini Imagen).
Shows visual watermarking with QR codes, steganography, and verification.

Usage:
    python 06_image_watermarking.py

Features:
    - Generate or load AI-generated images
    - Visual watermark overlay with transparency
    - QR code embedding for easy verification
    - Perceptual hashing for robustness
    - Save original, watermarked, and modified versions
    - Test tampering detection

Requirements:
    pip install Pillow qrcode
"""

import json
import os
import sys
from datetime import datetime
from io import BytesIO

# Set UTF-8 encoding for Windows console
if sys.platform == "win32":
    import codecs

    sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())

try:
    from PIL import Image, ImageDraw, ImageFont, ImageFilter

    PIL_AVAILABLE = True
except ImportError:
    PIL_AVAILABLE = False
    print("❌ PIL not available. Install with: pip install Pillow")
    exit(1)

from ciaf_watermarks import watermark_ai_output
from ciaf_watermarks.models import ArtifactType


def create_sample_ai_image(width: int = 1024, height: int = 768) -> bytes:
    """
    Create a sample AI-generated image for demonstration.

    In production, this would be replaced with actual AI image generation
    from models like Gemini Imagen, DALL-E, Midjourney, etc.

    Args:
        width: Image width in pixels
        height: Image height in pixels

    Returns:
        PNG image bytes
    """
    # Create a colorful gradient image (simulating AI-generated art)
    image = Image.new("RGB", (width, height))
    pixels = image.load()

    # Create gradient with some variation (simulating AI art)
    for y in range(height):
        for x in range(width):
            # Complex gradient mimicking AI-generated imagery
            r = int((x / width) * 255)
            g = int((y / height) * 255)
            b = int(((x + y) / (width + height)) * 255)
            pixels[x, y] = (r, g, b)

    # Add some "AI art" elements - circles to simulate generated content
    draw = ImageDraw.Draw(image)

    # Abstract circles (simulating AI-generated shapes)
    for i in range(10):
        x = (i * width) // 10
        y = height // 2
        radius = 50 + (i * 10)
        color = (255 - (i * 25), 100 + (i * 15), 200 - (i * 20))
        draw.ellipse([x - radius, y - radius, x + radius, y + radius], outline=color, width=3)

    # Add "AI-generated" text
    try:
        font = ImageFont.truetype("arial.tt", 48)
    except Exception:
        font = ImageFont.load_default()

    text = "AI-Generated Artwork"
    draw.text((width // 2 - 200, 50), text, fill=(255, 255, 255), font=font)

    # Convert to bytes
    buffer = BytesIO()
    image.save(buffer, format="PNG")
    return buffer.getvalue()


def display_image_info(image_bytes: bytes, label: str):
    """Display information about an image."""
    img = Image.open(BytesIO(image_bytes))
    print(f"\n{label}:")
    print(f"   - Format: {img.format}")
    print(f"   - Size: {img.size[0]}x{img.size[1]} pixels")
    print(f"   - Mode: {img.mode}")
    print(f"   - File size: {len(image_bytes):,} bytes ({len(image_bytes)/1024:.1f} KB)")


def create_modified_image(image_bytes: bytes) -> bytes:
    """
    Create a modified version of the image to test tampering detection.

    Applies various modifications that attackers might use:
    - Cropping
    - Filtering
    - Text addition
    - Compression

    Args:
        image_bytes: Original image bytes

    Returns:
        Modified image bytes
    """
    img = Image.open(BytesIO(image_bytes))

    # Apply modifications
    # 1. Slight crop (remove 5% from edges)
    width, height = img.size
    crop_margin = int(width * 0.05)
    img = img.crop((crop_margin, crop_margin, width - crop_margin, height - crop_margin))

    # 2. Apply slight blur filter
    img = img.filter(ImageFilter.GaussianBlur(radius=1))

    # 3. Add unauthorized text
    draw = ImageDraw.Draw(img)
    try:
        font = ImageFont.truetype("arial.tt", 36)
    except Exception:
        font = ImageFont.load_default()

    draw.text((50, height - 150), "[UNAUTHORIZED EDIT]", fill=(255, 0, 0), font=font)

    # 4. Save with compression
    buffer = BytesIO()
    img.save(buffer, format="PNG", optimize=True, quality=85)
    return buffer.getvalue()


def main():
    """Image watermarking example."""

    print("=" * 70)
    print("Google Gemini Imagen + CIAF Image Watermarking")
    print("=" * 70)

    if not PIL_AVAILABLE:
        print("\n❌ Pillow not installed. Install with:")
        print("   pip install Pillow")
        return

    # ========================================================================
    # 1. GENERATE/LOAD AI IMAGE
    # ========================================================================

    print("\n" + "=" * 70)
    print("🎨 Generating AI Image")
    print("=" * 70)

    # In production: This would be actual Gemini Imagen API call
    # image_bytes = gemini_imagen.generate(prompt="...", ...)

    # For demo: Create sample image
    prompt = "A futuristic cityscape at sunset with flying cars and neon lights, digital art style"
    print(f"\n📝 Prompt: {prompt}")
    print("\n🔄 Generating image (demo mode - sample image)...")

    original_image_bytes = create_sample_ai_image(1024, 768)

    display_image_info(original_image_bytes, "✅ Generated Image")

    # ========================================================================
    # 2. WATERMARK THE IMAGE
    # ========================================================================

    print("\n" + "=" * 70)
    print("💧 Watermarking Image")
    print("=" * 70)

    try:
        evidence, watermarked_image_bytes = watermark_ai_output(
            artifact=original_image_bytes,
            model_id="gemini-imagen-2.0",  # Future Gemini image model
            model_version="2.0",
            actor_id="user:image_demo",
            prompt=prompt,
            verification_base_url="https://verify.example.com",
            artifact_type=ArtifactType.IMAGE,
            watermark_config={
                "mode": "visual",
                "opacity": 0.4,
                "position": "bottom_left",
                "text": f"AI Generated: {datetime.now().strftime('%Y-%m-%d')}",
                "include_qr": True,  # Add QR code for easy verification
                "qr_position": "top_right",
            },
            enable_forensic_fragments=True,
        )

        print("\n✅ Watermarking successful!")
        print(f"   - Artifact ID: {evidence.artifact_id}")
        print(f"   - Watermark ID: {evidence.watermark.watermark_id}")
        print(f"   - Watermark Type: {evidence.watermark.watermark_type}")
        print(f"   - Embed Method: {evidence.watermark.embed_method}")

        if evidence.hashes.forensic_fragments:
            print(
                f"   - Image fragments captured: {len(evidence.hashes.forensic_fragments.all_fragments)}"
            )

        display_image_info(watermarked_image_bytes, "\n💧 Watermarked Image")

        # Calculate size impact
        size_increase = len(watermarked_image_bytes) - len(original_image_bytes)
        size_increase_pct = (size_increase / len(original_image_bytes)) * 100
        print(f"   - Size impact: +{size_increase:,} bytes (+{size_increase_pct:.2f}%)")

    except Exception as e:
        print(f"❌ Watermarking Error: {e}")
        import traceback

        traceback.print_exc()
        return

    # ========================================================================
    # 3. CREATE MODIFIED VERSION (TEST TAMPERING)
    # ========================================================================

    print("\n" + "=" * 70)
    print("🔧 Creating Modified Version (Tampering Test)")
    print("=" * 70)

    modified_image_bytes = create_modified_image(watermarked_image_bytes)

    print("\n✅ Modifications applied:")
    print("   1. Cropped edges (5% removed)")
    print("   2. Gaussian blur filter (radius=1)")
    print("   3. Added unauthorized text: '[UNAUTHORIZED EDIT]'")
    print("   4. Re-compressed with quality=85")

    display_image_info(modified_image_bytes, "\n🔧 Modified Image")

    # ========================================================================
    # 4. SAVE ALL ARTIFACTS
    # ========================================================================

    print("\n" + "=" * 70)
    print("💾 Saving Artifacts")
    print("=" * 70)

    # Create output directory
    output_dir = f"outputs/gemini_image/{evidence.artifact_id}"
    os.makedirs(output_dir, exist_ok=True)

    # Save all files
    files_saved = []

    # 1. Original image
    original_path = os.path.join(output_dir, "01_original.png")
    with open(original_path, "wb") as f:
        f.write(original_image_bytes)
    files_saved.append("01_original.png")

    # 2. Watermarked image
    watermarked_path = os.path.join(output_dir, "02_watermarked.png")
    with open(watermarked_path, "wb") as f:
        f.write(watermarked_image_bytes)
    files_saved.append("02_watermarked.png")

    # 3. Evidence JSON
    evidence_path = os.path.join(output_dir, "03_evidence.json")
    with open(evidence_path, "w", encoding="utf-8") as f:
        json.dump(evidence.to_dict(), f, indent=2)
    files_saved.append("03_evidence.json")

    # 4. Modified image
    modified_path = os.path.join(output_dir, "04_modified.png")
    with open(modified_path, "wb") as f:
        f.write(modified_image_bytes)
    files_saved.append("04_modified.png")

    print(f"\n✅ All artifacts saved to: {output_dir}/")
    print("\n📁 Files:")
    for filename in files_saved:
        filepath = os.path.join(output_dir, filename)
        size = os.path.getsize(filepath)
        print(f"   - {filename} ({size:,} bytes)")

    # ========================================================================
    # 5. VERIFY WATERMARKED IMAGE
    # ========================================================================

    print("\n" + "=" * 70)
    print("🔍 Verification Tests")
    print("=" * 70)

    from ciaf_watermarks.images import similarity_score, compute_perceptual_hash

    # For image verification, we use perceptual hashing to detect tampering
    # The hierarchical verification system provides full verification,
    # but for this demo we'll show a simpler approach

    # Test 1: Verify original watermarked image (should match exactly)
    print("\n📋 Test 1: Verify Watermarked Image (Original)")

    # Compute perceptual hash of current image
    watermarked_hash = compute_perceptual_hash(watermarked_image_bytes)

    # Check if we have stored fingerprints in evidence
    stored_hash = None
    if hasattr(evidence.hashes, "perceptual_hash_after"):
        stored_hash = evidence.hashes.perceptual_hash_after

    if stored_hash:
        similarity_original = similarity_score(watermarked_hash, stored_hash)
        print(f"   - Similarity to stored: {similarity_original:.2%}")
        print(f"   - Authentic: {similarity_original >= 0.95}")
        print("   - Watermark Present: Yes (visual watermark)")
        print("   - Content Modified: No")
    else:
        print(f"   - Hash computed: {watermarked_hash}")
        print("   - Note: No stored hash for comparison (evidence created)")

    # Test 2: Verify modified image (should show tampering)
    print("\n📋 Test 2: Verify Modified Image (Tampered)")

    modified_hash = compute_perceptual_hash(modified_image_bytes)

    if stored_hash or watermarked_hash:
        reference_hash = stored_hash if stored_hash else watermarked_hash
        similarity_modified = similarity_score(modified_hash, reference_hash)

        print(f"   - Similarity to original: {similarity_modified:.2%}")
        print(f"   - Authentic: {similarity_modified >= 0.95}")
        print(
            f"   - Watermark Present: {'Yes' if similarity_modified > 0.5 else 'Possibly Removed'}"
        )
        print(f"   - Content Modified: {similarity_modified < 0.95}")

        # Show confidence drop
        confidence_drop = 100.0 - similarity_modified * 100
        print(f"\n   ⚠️  Confidence Drop: {confidence_drop:.1f}% from original")
        print(
            f"   📊 Detection: Tampering {'DETECTED ✅' if similarity_modified < 0.95 else 'NOT DETECTED ❌'}"
        )

        result_original_confidence = similarity_original if stored_hash else 1.0
        result_modified_confidence = similarity_modified
    else:
        print(f"   - Hash computed: {modified_hash}")
        result_original_confidence = 1.0
        result_modified_confidence = 0.85  # Demo value

    # ========================================================================
    # 6. DISPLAY MODIFICATIONS
    # ========================================================================

    print("\n" + "=" * 70)
    print("🔬 Modification Analysis")
    print("=" * 70)

    original_img = Image.open(BytesIO(watermarked_image_bytes))
    modified_img = Image.open(BytesIO(modified_image_bytes))

    print("\n📊 Image Changes Detected:")
    print(f"   - Original size: {original_img.size[0]}x{original_img.size[1]}")
    print(f"   - Modified size: {modified_img.size[0]}x{modified_img.size[1]}")

    width_diff = abs(original_img.size[0] - modified_img.size[0])
    height_diff = abs(original_img.size[1] - modified_img.size[1])

    if width_diff > 0 or height_diff > 0:
        print(f"   - Dimension change: -{width_diff}x{height_diff} pixels")
        crop_pct = (width_diff * 2 / original_img.size[0]) * 100
        print(f"   - Crop percentage: ~{crop_pct:.1f}%")

    print("\n   ✅ Modifications:")
    print("      • Cropping applied")
    print("      • Blur filter applied")
    print("      • Unauthorized text added")
    print("      • Compression artifacts")

    # ========================================================================
    # SUMMARY
    # ========================================================================

    print("\n" + "=" * 70)
    print("✅ Image Watermarking Example Complete!")
    print("=" * 70)

    print("\n📊 Summary:")
    print("   - Model: Gemini Imagen 2.0 (demo)")
    print(f"   - Original size: {len(original_image_bytes):,} bytes")
    print(f"   - Watermarked size: {len(watermarked_image_bytes):,} bytes")
    print(f"   - Modified size: {len(modified_image_bytes):,} bytes")
    print(f"   - Artifacts saved: {len(files_saved)} files")
    print(f"   - Output directory: {output_dir}/")

    print("\n🔍 Verification Results:")
    print(f"   - Original: {result_original_confidence:.2%} confidence")
    print(f"   - Modified: {result_modified_confidence:.2%} confidence")

    tampering_detected = result_modified_confidence < 0.95
    print(f"   - Tampering: {'DETECTED ✅' if tampering_detected else 'NOT DETECTED ❌'}")

    print("\n💡 Key Features:")
    print("   1. Visual watermark with configurable transparency")
    print("   2. QR code embedding for mobile verification")
    print("   3. Perceptual image hashing (robust to compression)")
    print("   4. Forensic fragment sampling from high-entropy patches")
    print("   5. Tampering detection via similarity scoring")

    print("\n📁 Directory Structure:")
    print(f"   {output_dir}/")
    print("   ├── 01_original.png      (AI-generated image)")
    print("   ├── 02_watermarked.png   (With CIAF watermark + QR)")
    print("   ├── 03_evidence.json     (Forensic evidence)")
    print("   └── 04_modified.png      (Tampered version)")

    print("\n🎯 Best Practices:")
    print("   - Watermark immediately after generation")
    print("   - Store original + watermarked + evidence")
    print("   - Use QR codes for public verification")
    print("   - Monitor confidence scores for tampering")
    print("   - Archive evidence for forensic analysis")

    print("\n📚 Related Examples:")
    print("   - 01_basic_text_watermarking.py - Text watermarking")
    print("   - 02_chat_conversation.py - Multi-turn conversations")
    print("   - 07_video_watermarking.py - Video watermarking")


if __name__ == "__main__":
    main()
