"""
Google Gemini + CIAF Watermarking - Video Watermarking Example

Demonstrates watermarking videos generated by AI models (e.g., Veo, Sora, Runway).
Shows metadata watermarking, visual overlays, and forensic verification.

Usage:
    python 07_video_watermarking.py

Features:
    - Generate or load AI-generated videos
    - Metadata watermarking (fast, no re-encoding)
    - Visual watermark overlay with QR code
    - Temporal fingerprinting (I-frame sampling)
    - Save original, watermarked, and modified versions
    - Test tampering detection

Requirements:
    pip install ffmpeg-python opencv-python qrcode[pil] Pillow

Note:
    Requires FFmpeg installed on system:
    - Windows: Download from ffmpeg.org
    - Linux: sudo apt-get install ffmpeg
    - macOS: brew install ffmpeg
"""

import json
import os
import sys

# from datetime import datetime

# Set UTF-8 encoding for Windows console
if sys.platform == "win32":
    import codecs

    sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())

# Check for required dependencies
FFMPEG_AVAILABLE = False
OPENCV_AVAILABLE = False

try:
    import ffmpeg

    FFMPEG_AVAILABLE = True
except ImportError:
    print("⚠️  ffmpeg-python not available. Install with: pip install ffmpeg-python")

try:
    import cv2
    import numpy as np

    OPENCV_AVAILABLE = True
except ImportError:
    print("⚠️  OpenCV not available. Install with: pip install opencv-python")

if not FFMPEG_AVAILABLE or not OPENCV_AVAILABLE:
    print("\n❌ Missing dependencies. Install all requirements:")
    print("   pip install ffmpeg-python opencv-python qrcode[pil] Pillow")
    sys.exit(1)

from ciaf_watermarks import watermark_ai_output  # noqa: E402
from ciaf_watermarks.models import ArtifactType  # noqa: E402


def create_sample_ai_video(
    output_path: str, duration: int = 5, width: int = 1280, height: int = 720, fps: int = 30
) -> None:
    """
    Create a sample AI-generated video for demonstration.

    In production, this would be replaced with actual AI video generation
    from models like Veo, Sora, Runway Gen-2, Pika, etc.

    Args:
        output_path: Path to save video file
        duration: Duration in seconds
        width: Video width in pixels
        height: Video height in pixels
        fps: Frames per second
    """
    print("\n🎬 Creating sample AI-generated video...")
    print(f"   Resolution: {width}x{height}")
    print(f"   Duration: {duration}s @ {fps} fps")

    # Create AVI first (more reliable with OpenCV)
    temp_avi = output_path.replace(".mp4", "_temp.avi")

    # Use MJPEG codec for AVI (most compatible)
    fourcc = cv2.VideoWriter_fourcc(*"MJPG")
    out = cv2.VideoWriter(temp_avi, fourcc, fps, (width, height))

    if not out.isOpened():
        print("   ⚠️  Error: Could not create video writer")
        return

    total_frames = duration * fps

    for frame_num in range(total_frames):
        # Create animated gradient (simulating AI-generated video)
        frame = np.zeros((height, width, 3), dtype=np.uint8)

        # Animated color gradient
        t = frame_num / total_frames
        for y in range(height):
            for x in range(width):
                # Moving gradient effect
                r = int((x / width + t) * 255) % 255
                g = int((y / height + t) * 255) % 255
                b = int(((x + y) / (width + height) + t) * 255) % 255
                frame[y, x] = [b, g, r]  # OpenCV uses BGR

        # Add animated circle (simulating AI motion)
        center_x = int(width / 2 + width / 3 * np.sin(2 * np.pi * t))
        center_y = int(height / 2 + height / 3 * np.cos(2 * np.pi * t))
        radius = int(50 + 30 * np.sin(4 * np.pi * t))
        cv2.circle(frame, (center_x, center_y), radius, (255, 255, 255), 3)

        # Add frame counter
        text = f"Frame {frame_num + 1}/{total_frames}"
        cv2.putText(
            frame, text, (20, 40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA
        )

        # Add "AI-Generated" text
        cv2.putText(
            frame,
            "AI-Generated Video",
            (width // 2 - 200, height - 40),
            cv2.FONT_HERSHEY_SIMPLEX,
            1.2,
            (255, 255, 255),
            3,
            cv2.LINE_AA,
        )

        out.write(frame)

        # Progress indicator
        if (frame_num + 1) % 30 == 0:
            progress = (frame_num + 1) / total_frames * 100
            print(f"   Progress: {progress:.0f}%", end="\r")

    out.release()
    print(f"\n   ✅ AVI created: {temp_avi}")

    # Convert AVI to MP4 using ffmpeg for better compatibility
    try:
        print("   🔄 Converting to MP4...")
        (
            ffmpeg.input(temp_avi)
            .output(output_path, vcodec="libx264", pix_fmt="yuv420p", **{"b:v": "2M"})
            .overwrite_output()
            .run(quiet=True)
        )

        # Clean up temporary AVI
        if os.path.exists(temp_avi):
            os.remove(temp_avi)

        print(f"   ✅ Video created: {output_path}")
    except Exception as e:
        print(f"   ⚠️  ffmpeg conversion failed: {e}")
        # Keep the AVI file as fallback
        if os.path.exists(temp_avi):
            os.rename(temp_avi, output_path.replace(".mp4", ".avi"))
            print(f"   ✅ AVI file available instead: {output_path.replace('.mp4', '.avi')}")


def display_video_info(video_path: str, label: str):
    """Display information about a video file."""
    print(f"\n📹 {label}:")

    if not os.path.exists(video_path):
        print(f"   ❌ File not found: {video_path}")
        return

    try:
        probe = ffmpeg.probe(video_path)
        video_stream = next((s for s in probe["streams"] if s["codec_type"] == "video"), None)
        format_info = probe["format"]

        if video_stream:
            width = int(video_stream.get("width", 0))
            height = int(video_stream.get("height", 0))
            fps = eval(video_stream.get("r_frame_rate", "0/1"))
            codec = video_stream.get("codec_name", "unknown")
            duration = float(format_info.get("duration", 0))
            size_mb = float(format_info.get("size", 0)) / (1024 * 1024)

            print(f"   - Resolution: {width}x{height}")
            print(f"   - Duration: {duration:.2f}s")
            print(f"   - FPS: {fps:.2f}")
            print(f"   - Codec: {codec}")
            print(f"   - Size: {size_mb:.2f} MB")

            # Check for metadata watermark
            if "tags" in format_info:
                tags = format_info["tags"]
                if "comment" in tags or "description" in tags:
                    print("   - Metadata: Present")
                    if "comment" in tags and "wmk-" in tags["comment"]:
                        print("   - Watermark ID: Found in metadata")
        else:
            print(f"   - Size: {os.path.getsize(video_path)} bytes")
            print("   - Could not extract video stream info")

    except Exception as e:
        print(f"   ⚠️  Error reading video info: {e}")
        print(f"   - Size: {os.path.getsize(video_path)} bytes")


def main():
    """Video watermarking demonstration."""

    print("=" * 70)
    print("Google Gemini Video Watermarking Example")
    print("=" * 70)

    # ========================================================================
    # 1. SETUP - Create sample AI-generated video
    # ========================================================================

    print("\n📋 Setup:")
    print("   This example demonstrates video watermarking for AI-generated content.")
    print("   In production, you'd watermark videos from Veo, Sora, Runway, etc.")

    # Create output directories
    output_dir = "outputs/gemini_video"
    os.makedirs(output_dir, exist_ok=True)

    original_video_path = os.path.join(output_dir, "01_original.mp4")

    # Create sample video if it doesn't exist
    if not os.path.exists(original_video_path):
        create_sample_ai_video(original_video_path, duration=5, width=1280, height=720, fps=30)
    else:
        print(f"\n✅ Using existing video: {original_video_path}")

    display_video_info(original_video_path, "Original Video")

    # Read video as bytes
    with open(original_video_path, "rb") as f:
        video_bytes = f.read()

    # ========================================================================
    # 2. WATERMARK WITH METADATA (Recommended - Fast, No Re-encoding)
    # ========================================================================

    print("\n" + "=" * 70)
    print("Watermarking Method: Metadata Injection")
    print("=" * 70)
    print("\n💧 Applying metadata watermark...")
    print("   - Method: Metadata injection (no re-encoding)")
    print("   - Speed: Fast (~100-500ms)")
    print("   - Quality: Lossless (original video unchanged)")

    try:
        evidence, watermarked_bytes = watermark_ai_output(
            artifact=video_bytes,
            artifact_type=ArtifactType.VIDEO,
            model_id="veo-2",
            model_version="2026-03",
            actor_id="user:director-alice",
            prompt="Create cinematic coastal landscape with drone movement",
            verification_base_url="https://vault.google.com",
            watermark_config={
                "mode": "metadata",
            },
        )

        print("✅ Watermarking successful!")
        print("\n📊 Evidence Record:")
        print(f"   - Artifact ID: {evidence.artifact_id}")
        print(f"   - Watermark ID: {evidence.watermark.watermark_id}")
        print(f"   - Model: {evidence.model_id} v{evidence.model_version}")
        print(f"   - Actor: {evidence.actor_id}")
        print(f"   - Watermark Type: {evidence.watermark.watermark_type}")
        print(f"   - Embed Method: {evidence.watermark.embed_method}")

        # Display hash information
        print("\n🔐 Cryptographic Hashes:")
        print(f"   - Hash (before): {evidence.hashes.content_hash_before_watermark[:16]}...")
        print(f"   - Hash (after):  {evidence.hashes.content_hash_after_watermark[:16]}...")

        # Display metadata
        if evidence.metadata:
            print("\n📝 Video Metadata:")
            if "duration_seconds" in evidence.metadata:
                print(f"   - Duration: {evidence.metadata['duration_seconds']}s")
            if "width" in evidence.metadata:
                print(
                    f"   - Resolution: {evidence.metadata['width']}x{evidence.metadata['height']}"
                )
            if "fps" in evidence.metadata:
                print(f"   - FPS: {evidence.metadata['fps']}")
            if "codec" in evidence.metadata:
                print(f"   - Codec: {evidence.metadata['codec']}")

        # Save watermarked video
        watermarked_path = os.path.join(output_dir, "02_watermarked_metadata.mp4")
        with open(watermarked_path, "wb") as f:
            f.write(watermarked_bytes)
        print(f"\n✅ Saved watermarked video: {watermarked_path}")

        display_video_info(watermarked_path, "Watermarked Video (Metadata)")

        # Save evidence
        evidence_path = os.path.join(output_dir, "03_evidence.json")
        with open(evidence_path, "w") as f:
            json.dump(evidence.to_dict(), f, indent=2)
        print(f"✅ Saved evidence: {evidence_path}")

    except Exception as e:
        print(f"❌ Watermarking Error: {e}")
        import traceback

        traceback.print_exc()
        return

    # ========================================================================
    # 3. VERIFY WATERMARKED VIDEO
    # ========================================================================

    print("\n" + "=" * 70)
    print("Verification Test")
    print("=" * 70)

    print("\n🔍 Verifying watermarked video...")

    try:
        from ciaf_watermarks.video.verification import verify_video_artifact

        verification_result = verify_video_artifact(watermarked_bytes, evidence)

        print("\n✅ Verification Result:")
        print(f"   - Authentic: {verification_result.is_authentic()}")
        print(f"   - Confidence: {verification_result.confidence:.1%}")
        print(f"   - Watermark Present: {verification_result.watermark_present}")

        if verification_result.notes:
            print(f"   - Notes: {verification_result.notes[0]}")

    except ImportError:
        print("⚠️  Video verification module not fully implemented")
        print("   Using hash-based verification instead...")

        # Fallback: Basic hash verification
        from ciaf_watermarks.hashing import sha256_bytes

        suspect_hash = sha256_bytes(watermarked_bytes)
        exact_match = suspect_hash == evidence.hashes.content_hash_after_watermark

        print("\n✅ Hash Verification:")
        print(f"   - Exact Match: {exact_match}")
        print(f"   - Confidence: {100 if exact_match else 0}%")

    # ========================================================================
    # 4. TEST TAMPERING DETECTION
    # ========================================================================

    print("\n" + "=" * 70)
    print("Tampering Detection Test")
    print("=" * 70)

    print("\n🔬 Testing tampering detection...")
    print("   Scenario: Re-encode video to strip metadata")

    try:
        # Re-encode video to strip metadata (simulating tampering)
        stripped_path = os.path.join(output_dir, "04_stripped_metadata.mp4")

        # Use ffmpeg to re-encode (which strips metadata in custom fields)
        (
            ffmpeg.input(watermarked_path)
            .output(stripped_path, vcodec="libx264", acodec="copy")
            .overwrite_output()
            .run(quiet=True)
        )

        print(f"✅ Created stripped version: {stripped_path}")
        display_video_info(stripped_path, "Stripped Video (Metadata Removed)")

        # Verify stripped version
        with open(stripped_path, "rb") as f:
            stripped_bytes = f.read()

        from ciaf_watermarks.hashing import sha256_bytes

        stripped_hash = sha256_bytes(stripped_bytes)

        print("\n🔍 Verification of Stripped Video:")
        exact_match_after = stripped_hash == evidence.hashes.content_hash_after_watermark
        exact_match_before = stripped_hash == evidence.hashes.content_hash_before_watermark

        if exact_match_after:
            print("   - Status: ✅ Authentic (exact match)")
            print("   - Confidence: 100%")
        elif exact_match_before:
            print("   - Status: ⚠️  Watermark removed!")
            print("   - Confidence: 95% (matches original)")
            print("   - Detection: Metadata was stripped")
        else:
            print("   - Status: ⚠️  Modified")
            print("   - Note: Re-encoding changed video data")
            print("   - Recommendation: Use visual watermarking for re-encode resistance")

    except Exception as e:
        print(f"⚠️  Tampering test error: {e}")

    # ========================================================================
    # 5. VISUAL WATERMARKING (Optional - For Re-encode Resistance)
    # ========================================================================

    print("\n" + "=" * 70)
    print("Visual Watermarking (Re-encode Resistant)")
    print("=" * 70)
    print("\n💡 Note: Visual watermarks survive re-encoding but require processing time")
    print("   ⚠️  Visual watermarking requires proper FFmpeg/fontconfig setup")
    print("   On Windows, this may require additional configuration")

    try:
        print("\n💧 Applying visual watermark with QR code...")

        evidence_visual, watermarked_visual = watermark_ai_output(
            artifact=video_bytes,
            artifact_type=ArtifactType.VIDEO,
            model_id="veo-2",
            model_version="2026-03",
            actor_id="user:director-alice",
            prompt="Create cinematic coastal landscape with drone movement",
            verification_base_url="https://vault.google.com",
            watermark_config={
                "mode": "visual",
                "text": "AI Generated Video",
                "position": "bottom_right",
                "opacity": 0.6,
                "include_qr": True,
            },
        )

        visual_path = os.path.join(output_dir, "05_watermarked_visual.mp4")
        with open(visual_path, "wb") as f:
            f.write(watermarked_visual)

        print(f"✅ Saved visually watermarked video: {visual_path}")
        display_video_info(visual_path, "Watermarked Video (Visual + QR)")

        print("\n💡 Visual watermarking complete!")
        print("   - Survives re-encoding and format conversion")
        print("   - QR code can be scanned for instant verification")
        print("   - Semi-transparent overlay maintains video quality")

    except ImportError:
        print("⚠️  Visual watermarking requires additional dependencies")
        print("   Install: pip install qrcode[pil] Pillow")
    except Exception as e:
        error_msg = str(e)

        if "Fontconfig" in error_msg or "font" in error_msg.lower():
            print("⚠️  Visual watermarking failed: FFmpeg fontconfig issue (Windows)")
            print("\n💡 This is a known Windows FFmpeg limitation for text overlays.")
            print("   Workarounds:")
            print("   1. Use metadata watermarking instead (already working above)")
            print("   2. Use OpenCV-based visual watermarking (alternative method)")
            print("   3. Install full FFmpeg build with fontconfig support")
            print("   4. On production servers, use Linux where fontconfig works")
            print("\n   Note: Metadata watermarking is often preferred anyway (faster, lossless)")
        else:
            print(f"⚠️  Visual watermarking error: {error_msg}")
            print("   Visual watermarking is optional - metadata watermarking is working")

    # ========================================================================
    # SUMMARY
    # ========================================================================

    print("\n" + "=" * 70)
    print("Summary")
    print("=" * 70)

    print("\n📊 Generated Files:")
    files = [
        ("01_original.mp4", "Original AI-generated video"),
        ("02_watermarked_metadata.mp4", "Metadata watermark (fast, lossless)"),
        ("03_evidence.json", "Forensic evidence record"),
        ("04_stripped_metadata.mp4", "Tampered version (metadata removed)"),
    ]

    if os.path.exists(os.path.join(output_dir, "05_watermarked_visual.mp4")):
        files.append(("05_watermarked_visual.mp4", "Visual watermark (re-encode resistant)"))

    for filename, description in files:
        path = os.path.join(output_dir, filename)
        if os.path.exists(path):
            size_mb = os.path.getsize(path) / (1024 * 1024)
            print(f"   ✅ {filename:30s} - {description} ({size_mb:.2f} MB)")

    print("\n💡 Watermarking Methods Comparison:")
    print("   • Metadata: Fast, lossless, but removable via re-encoding")
    print("   • Visual: Slower, lossy, but survives re-encoding and format conversion")
    print("   • Hybrid: Best of both - metadata + visual overlay")

    if not os.path.exists(os.path.join(output_dir, "05_watermarked_visual.mp4")):
        print("\n   ℹ️  Note: Visual watermarking skipped (requires fontconfig on Windows)")
        print("      Metadata watermarking is recommended for most use cases anyway.")

    print("\n🎯 Production Recommendations:")
    print("   1. Use metadata watermarking for internal tracking (fast)")
    print("   2. Use visual watermarking for public distribution (tamper-resistant)")
    print("   3. Use hybrid mode for maximum protection")
    print("   4. Store evidence records in secure vault")
    print("   5. Implement verification API for users to check authenticity")

    print("\n📚 Related Examples:")
    print("   - 01_basic_text_watermarking.py - Text watermarking")
    print("   - 06_image_watermarking.py - Image watermarking")
    print("   - 08_audio_watermarking.py - Audio watermarking")
    print("   - 05_verification.py - Verification workflows")

    print(f"\n✅ Example complete! Check output directory: {output_dir}/")


if __name__ == "__main__":
    main()
