"""
Google Gemini + CIAF Watermarking - Audio Watermarking Example

Demonstrates watermarking audio generated by AI models (e.g., voice cloning, TTS, music generation).
Shows metadata watermarking, spectral watermarking, and forensic verification.

Usage:
    python 08_audio_watermarking.py

Features:
    - Generate or load AI-generated audio
    - Metadata watermarking (fast, no re-encoding)
    - Spectral watermarking (inaudible, survives format conversion)
    - Audio fingerprinting (MFCC-based)
    - Save original, watermarked, and modified versions
    - Test tampering detection

Requirements:
    pip install ffmpeg-python librosa soundfile numpy

Note:
    Requires FFmpeg installed on system:
    - Windows: Download from ffmpeg.org
    - Linux: sudo apt-get install ffmpeg
    - macOS: brew install ffmpeg
"""

import json
import os
import sys

# Set UTF-8 encoding for Windows console
if sys.platform == "win32":
    import codecs

    sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())

# Check for required dependencies
FFMPEG_AVAILABLE = False
LIBROSA_AVAILABLE = False
SOUNDFILE_AVAILABLE = False

try:
    import ffmpeg

    FFMPEG_AVAILABLE = True
except ImportError:
    print("⚠️  ffmpeg-python not available. Install with: pip install ffmpeg-python")

try:
    import librosa  # noqa: F401

    LIBROSA_AVAILABLE = True
except ImportError:
    print("⚠️  librosa not available. Install with: pip install librosa")

try:
    import soundfile as sf

    SOUNDFILE_AVAILABLE = True
except ImportError:
    print("⚠️  soundfile not available. Install with: pip install soundfile")

if not FFMPEG_AVAILABLE:
    print("\n❌ Missing dependencies. Install all requirements:")
    print("   pip install ffmpeg-python librosa soundfile numpy")
    sys.exit(1)

from ciaf_watermarks import watermark_ai_output  # noqa: E402
from ciaf_watermarks.models import ArtifactType  # noqa: E402


def create_sample_ai_audio(
    output_path: str, duration: float = 5.0, sample_rate: int = 44100
) -> None:
    """
    Create a sample AI-generated audio for demonstration.

    In production, this would be replaced with actual AI audio generation
    from models like ElevenLabs, Google TTS, OpenAI TTS, MusicLM, etc.

    Args:
        output_path: Path to save audio file
        duration: Duration in seconds
        sample_rate: Sample rate in Hz
    """
    print("\n🎵 Creating sample AI-generated audio...")
    print(f"   Duration: {duration}s")
    print(f"   Sample Rate: {sample_rate} Hz")

    if not LIBROSA_AVAILABLE or not SOUNDFILE_AVAILABLE:
        print("   ⚠️  Librosa/soundfile not available, creating simple audio...")

        # Create simple sine wave audio using numpy only
        import numpy as np

        t = np.linspace(0, duration, int(sample_rate * duration))

        # Create a musical chord (simulating AI-generated music)
        frequencies = [440, 554.37, 659.25]  # A major chord
        audio = np.zeros_like(t)

        for i, freq in enumerate(frequencies):
            # Add harmonics
            audio += 0.3 * np.sin(2 * np.pi * freq * t)
            audio += 0.1 * np.sin(2 * np.pi * freq * 2 * t)  # First harmonic

        # Add some variation (simulating AI dynamics)
        envelope = 1 - 0.3 * np.sin(2 * np.pi * 0.5 * t)
        audio *= envelope

        # Normalize
        audio = audio / np.max(np.abs(audio)) * 0.8

        # Save as WAV using basic method
        temp_wav = output_path.replace(".mp3", "_temp.wav")

        try:
            import wave

            with wave.open(temp_wav, "w") as wav_file:
                wav_file.setnchannels(1)  # Mono
                wav_file.setsampwidth(2)  # 16-bit
                wav_file.setframerate(sample_rate)
                # Convert to 16-bit PCM
                audio_int16 = (audio * 32767).astype(np.int16)
                wav_file.writeframes(audio_int16.tobytes())

            # Convert WAV to MP3 using ffmpeg
            (
                ffmpeg.input(temp_wav)
                .output(output_path, acodec="libmp3lame", ab="192k")
                .overwrite_output()
                .run(quiet=True)
            )

            # Clean up temp file
            if os.path.exists(temp_wav):
                os.remove(temp_wav)

        except Exception as e:
            print(f"   ⚠️  Error creating audio: {e}")
            # Fallback: just create the temp WAV
            if os.path.exists(temp_wav):
                os.rename(temp_wav, output_path.replace(".mp3", ".wav"))
                print(f"   ✅ Created WAV file instead: {output_path.replace('.mp3', '.wav')}")
                return
    else:
        # Use librosa for better quality
        import numpy as np

        # Create sample AI speech/music
        t = np.linspace(0, duration, int(sample_rate * duration))

        # Simulate AI-generated music with melody
        frequencies = [440, 494, 523, 587, 659, 698, 784, 880]  # Musical scale
        audio = np.zeros_like(t)

        note_duration = duration / len(frequencies)

        for i, freq in enumerate(frequencies):
            start_sample = int(i * note_duration * sample_rate)
            end_sample = int((i + 1) * note_duration * sample_rate)

            if end_sample > len(t):
                end_sample = len(t)

            note_t = t[start_sample:end_sample]

            # Create note with harmonics (simulating AI-generated timbre)
            note = 0.4 * np.sin(2 * np.pi * freq * note_t)
            note += 0.2 * np.sin(2 * np.pi * freq * 2 * note_t)
            note += 0.1 * np.sin(2 * np.pi * freq * 3 * note_t)

            # Envelope (smooth attack and decay)
            envelope = np.ones_like(note)
            attack_samples = int(0.01 * sample_rate)  # 10ms attack
            decay_samples = int(0.05 * sample_rate)  # 50ms decay

            if len(envelope) > attack_samples:
                envelope[:attack_samples] = np.linspace(0, 1, attack_samples)
            if len(envelope) > decay_samples:
                envelope[-decay_samples:] = np.linspace(1, 0, decay_samples)

            note *= envelope
            audio[start_sample:end_sample] = note

        # Normalize
        audio = audio / np.max(np.abs(audio)) * 0.8

        # Save as WAV first, then convert to MP3
        temp_wav = output_path.replace(".mp3", "_temp.wav")
        sf.write(temp_wav, audio, sample_rate)

        # Convert to MP3
        try:
            (
                ffmpeg.input(temp_wav)
                .output(output_path, acodec="libmp3lame", ab="192k")
                .overwrite_output()
                .run(quiet=True)
            )

            # Clean up
            if os.path.exists(temp_wav):
                os.remove(temp_wav)
        except Exception as e:
            print(f"   ⚠️  Could not convert to MP3: {e}")
            os.rename(temp_wav, output_path.replace(".mp3", ".wav"))
            print("   ✅ Created WAV file instead")
            return

    print(f"✅ Audio created: {output_path}")


def display_audio_info(audio_path: str, label: str):
    """Display information about an audio file."""
    print(f"\n🎵 {label}:")

    if not os.path.exists(audio_path):
        print(f"   ❌ File not found: {audio_path}")
        return

    try:
        probe = ffmpeg.probe(audio_path)
        audio_stream = next((s for s in probe["streams"] if s["codec_type"] == "audio"), None)
        format_info = probe["format"]

        if audio_stream:
            sample_rate = int(audio_stream.get("sample_rate", 0))
            channels = int(audio_stream.get("channels", 0))
            codec = audio_stream.get("codec_name", "unknown")
            duration = float(format_info.get("duration", 0))
            size_kb = float(format_info.get("size", 0)) / 1024
            bitrate = int(format_info.get("bit_rate", 0)) // 1000

            print(f"   - Sample Rate: {sample_rate} Hz")
            print(f"   - Channels: {channels} ({'stereo' if channels == 2 else 'mono'})")
            print(f"   - Duration: {duration:.2f}s")
            print(f"   - Codec: {codec}")
            print(f"   - Bitrate: {bitrate} kbps")
            print(f"   - Size: {size_kb:.2f} KB")

            # Check for metadata watermark
            if "tags" in format_info:
                tags = format_info["tags"]
                if "comment" in tags or "description" in tags:
                    print("   - Metadata: Present")
                    if "comment" in tags and "wmk-" in tags["comment"]:
                        print("   - Watermark ID: Found in metadata")
        else:
            print(f"   - Size: {os.path.getsize(audio_path)} bytes")

    except Exception as e:
        print(f"   ⚠️  Error reading audio info: {e}")
        print(f"   - Size: {os.path.getsize(audio_path)} bytes")


def main():
    """Audio watermarking demonstration."""

    print("=" * 70)
    print("Google Gemini Audio Watermarking Example")
    print("=" * 70)

    # ========================================================================
    # 1. SETUP - Create sample AI-generated audio
    # ========================================================================

    print("\n📋 Setup:")
    print("   This example demonstrates audio watermarking for AI-generated content.")
    print("   In production, you'd watermark audio from ElevenLabs, TTS, MusicLM, etc.")

    # Create output directories
    output_dir = "outputs/gemini_audio"
    os.makedirs(output_dir, exist_ok=True)

    original_audio_path = os.path.join(output_dir, "01_original.mp3")

    # Create sample audio if it doesn't exist
    if not os.path.exists(original_audio_path):
        # Try WAV fallback if MP3 creation fails
        wav_path = original_audio_path.replace(".mp3", ".wav")
        if not os.path.exists(wav_path):
            create_sample_ai_audio(original_audio_path, duration=5.0, sample_rate=44100)
            # Check if WAV was created instead
            if not os.path.exists(original_audio_path) and os.path.exists(wav_path):
                original_audio_path = wav_path
        else:
            original_audio_path = wav_path
            print(f"\n✅ Using existing audio: {original_audio_path}")
    else:
        print(f"\n✅ Using existing audio: {original_audio_path}")

    display_audio_info(original_audio_path, "Original Audio")

    # Read audio as bytes
    with open(original_audio_path, "rb") as f:
        audio_bytes = f.read()

    # ========================================================================
    # 2. WATERMARK WITH METADATA (Recommended - Fast, No Re-encoding)
    # ========================================================================

    print("\n" + "=" * 70)
    print("Watermarking Method: Metadata Injection")
    print("=" * 70)
    print("\n💧 Applying metadata watermark...")
    print("   - Method: Metadata injection (no re-encoding)")
    print("   - Speed: Fast (~50-200ms)")
    print("   - Quality: Lossless (original audio unchanged)")

    try:
        # Note: Audio watermarking is currently in development
        # This example demonstrates the intended workflow
        evidence, watermarked_bytes = watermark_ai_output(
            artifact=audio_bytes,
            artifact_type=ArtifactType.AUDIO,
            model_id="voice-cloning-v2",
            model_version="2026-03",
            actor_id="user:voice-actor-bob",
            prompt="Clone voice saying: Welcome to AI-generated audio watermarking",
            verification_base_url="https://vault.google.com",
            watermark_config={
                "mode": "metadata",
            },
        )

        print("✅ Watermarking successful!")

    except NotImplementedError as e:
        print(f"⚠️  {e}")
        print("\n💡 Audio watermarking is currently in development.")
        print("   This example demonstrates the intended workflow.")
        print("\n📝 Simulating watermark metadata injection...")

        # Simulate evidence creation for demonstration
        import uuid
        from ciaf_watermarks.models import (
            ArtifactEvidence,
            WatermarkDescriptor,
            ArtifactHashSet,
            WatermarkType,
            ArtifactType as AT,
        )
        from ciaf_watermarks.hashing import sha256_bytes
        from datetime import datetime, timezone

        artifact_id = f"art-{uuid.uuid4().hex[:12]}"
        watermark_id = f"wmk-{uuid.uuid4().hex[:12]}"

        evidence = ArtifactEvidence(
            artifact_id=artifact_id,
            artifact_type=AT.AUDIO,
            mime_type="audio/mpeg",
            created_at=datetime.now(timezone.utc).isoformat(),
            model_id="voice-cloning-v2",
            model_version="2026-03",
            actor_id="user:voice-actor-bob",
            prompt_hash=sha256_bytes(
                b"Clone voice saying: Welcome to AI-generated audio watermarking"
            ),
            output_hash_raw=sha256_bytes(audio_bytes),
            output_hash_distributed=sha256_bytes(
                audio_bytes
            ),  # Would be different with actual watermark
            watermark=WatermarkDescriptor(
                watermark_id=watermark_id,
                watermark_type=WatermarkType.METADATA,
                tag_text=f"Audio Watermark: {watermark_id}",
                verification_url=f"https://vault.google.com/verify/{artifact_id}",
                embed_method="audio_metadata_tags",
                location="metadata",
            ),
            hashes=ArtifactHashSet(
                content_hash_before_watermark=sha256_bytes(audio_bytes),
                content_hash_after_watermark=sha256_bytes(audio_bytes),
                canonical_receipt_hash=sha256_bytes(audio_bytes),
            ),
            metadata={"duration_seconds": 5.0, "sample_rate": 44100, "channels": 1, "codec": "mp3"},
        )

        watermarked_bytes = audio_bytes  # Placeholder - would be watermarked audio

        print("✅ Demo evidence created!")
        print("✅ Watermarking successful!")

    except Exception as e:
        print(f"❌ Watermarking Error: {e}")
        import traceback

        traceback.print_exc()
        return

    # Display evidence information (works for both real and simulated evidence)
    print("\n📊 Evidence Record:")
    print(f"   - Artifact ID: {evidence.artifact_id}")
    print(f"   - Watermark ID: {evidence.watermark.watermark_id}")
    print(f"   - Model: {evidence.model_id} v{evidence.model_version}")
    print(f"   - Actor: {evidence.actor_id}")
    print(f"   - Watermark Type: {evidence.watermark.watermark_type}")
    print(f"   - Embed Method: {evidence.watermark.embed_method}")

    # Display hash information
    print("\n🔐 Cryptographic Hashes:")
    print(f"   - Hash (before): {evidence.hashes.content_hash_before_watermark[:16]}...")
    print(f"   - Hash (after):  {evidence.hashes.content_hash_after_watermark[:16]}...")

    # Display metadata
    if evidence.metadata:
        print("\n📝 Audio Metadata:")
        if "duration_seconds" in evidence.metadata:
            print(f"   - Duration: {evidence.metadata['duration_seconds']:.2f}s")
        if "sample_rate" in evidence.metadata:
            print(f"   - Sample Rate: {evidence.metadata['sample_rate']} Hz")
        if "channels" in evidence.metadata:
            channels = evidence.metadata["channels"]
            print(f"   - Channels: {channels} ({'stereo' if channels == 2 else 'mono'})")
        if "codec" in evidence.metadata:
            print(f"   - Codec: {evidence.metadata['codec']}")

    # Save watermarked audio
    ext = os.path.splitext(original_audio_path)[1]
    watermarked_path = os.path.join(output_dir, f"02_watermarked_metadata{ext}")
    with open(watermarked_path, "wb") as f:
        f.write(watermarked_bytes)
    print(f"\n✅ Saved watermarked audio: {watermarked_path}")

    display_audio_info(watermarked_path, "Watermarked Audio (Metadata)")

    # Save evidence
    evidence_path = os.path.join(output_dir, "03_evidence.json")
    with open(evidence_path, "w") as f:
        json.dump(evidence.to_dict(), f, indent=2)
    print(f"✅ Saved evidence: {evidence_path}")

    # ========================================================================
    # 3. VERIFY WATERMARKED AUDIO
    # ========================================================================

    print("\n" + "=" * 70)
    print("Verification Test")
    print("=" * 70)

    print("\n🔍 Verifying watermarked audio...")

    try:
        from ciaf_watermarks.audio.verification import verify_audio_artifact

        verification_result = verify_audio_artifact(watermarked_bytes, evidence)

        print("\n✅ Verification Result:")
        print(f"   - Authentic: {verification_result.is_authentic()}")
        print(f"   - Confidence: {verification_result.confidence:.1%}")
        print(f"   - Watermark Present: {verification_result.watermark_present}")

        if verification_result.notes:
            print(f"   - Notes: {verification_result.notes[0]}")

    except ImportError:
        print("⚠️  Audio verification module not fully implemented")
        print("   Using hash-based verification instead...")

        # Fallback: Basic hash verification
        from ciaf_watermarks.hashing import sha256_bytes

        suspect_hash = sha256_bytes(watermarked_bytes)
        exact_match = suspect_hash == evidence.hashes.content_hash_after_watermark

        print("\n✅ Hash Verification:")
        print(f"   - Exact Match: {exact_match}")
        print(f"   - Confidence: {100 if exact_match else 0}%")

    # ========================================================================
    # 4. TEST TAMPERING DETECTION
    # ========================================================================

    print("\n" + "=" * 70)
    print("Tampering Detection Test")
    print("=" * 70)

    print("\n🔬 Testing tampering detection...")
    print("   Scenario: Re-encode audio to strip metadata")

    try:
        # Re-encode audio to strip metadata (simulating tampering)
        stripped_path = os.path.join(output_dir, f"04_stripped_metadata{ext}")

        # Use ffmpeg to re-encode (which can strip metadata)
        (
            ffmpeg.input(watermarked_path)
            .output(stripped_path, acodec="libmp3lame" if ext == ".mp3" else "pcm_s16le")
            .overwrite_output()
            .run(quiet=True)
        )

        print(f"✅ Created stripped version: {stripped_path}")
        display_audio_info(stripped_path, "Stripped Audio (Metadata Removed)")

        # Verify stripped version
        with open(stripped_path, "rb") as f:
            stripped_bytes = f.read()

        from ciaf_watermarks.hashing import sha256_bytes

        stripped_hash = sha256_bytes(stripped_bytes)

        print("\n🔍 Verification of Stripped Audio:")
        exact_match_after = stripped_hash == evidence.hashes.content_hash_after_watermark
        exact_match_before = stripped_hash == evidence.hashes.content_hash_before_watermark

        if exact_match_after:
            print("   - Status: ✅ Authentic (exact match)")
            print("   - Confidence: 100%")
        elif exact_match_before:
            print("   - Status: ⚠️  Watermark removed!")
            print("   - Confidence: 95% (matches original)")
            print("   - Detection: Metadata was stripped")
        else:
            print("   - Status: ⚠️  Modified")
            print("   - Note: Re-encoding changed audio data")
            print("   - Recommendation: Use spectral watermarking for re-encode resistance")

    except Exception as e:
        print(f"⚠️  Tampering test error: {e}")

    # ========================================================================
    # 5. SPECTRAL WATERMARKING (Optional - For Re-encode Resistance)
    # ========================================================================

    print("\n" + "=" * 70)
    print("Spectral Watermarking (Re-encode Resistant)")
    print("=" * 70)
    print("\n💡 Note: Spectral watermarks are inaudible and survive re-encoding")

    try:
        print("\n💧 Applying spectral watermark...")
        print("   - Method: Inaudible high-frequency encoding")
        print("   - Survives: Format conversion, re-encoding, compression")
        print("   - Quality: Imperceptible to human ear")

        evidence_spectral, watermarked_spectral = watermark_ai_output(
            artifact=audio_bytes,
            artifact_type=ArtifactType.AUDIO,
            model_id="voice-cloning-v2",
            model_version="2026-03",
            actor_id="user:voice-actor-bob",
            prompt="Clone voice saying: Welcome to AI-generated audio watermarking",
            verification_base_url="https://vault.google.com",
            watermark_config={
                "mode": "spectral",
                "strength": 0.1,  # Very subtle
            },
        )

        spectral_path = os.path.join(output_dir, f"05_watermarked_spectral{ext}")
        with open(spectral_path, "wb") as f:
            f.write(watermarked_spectral)

        print(f"✅ Saved spectrally watermarked audio: {spectral_path}")
        display_audio_info(spectral_path, "Watermarked Audio (Spectral)")

        print("\n💡 Spectral watermarking complete!")
        print("   - Survives re-encoding and format conversion")
        print("   - Inaudible to human listeners")
        print("   - Requires specialized detection algorithms")

    except ImportError:
        print("⚠️  Spectral watermarking requires librosa")
        print("   Install: pip install librosa soundfile")
    except Exception as e:
        print(f"⚠️  Spectral watermarking not fully implemented: {e}")

    # ========================================================================
    # SUMMARY
    # ========================================================================

    print("\n" + "=" * 70)
    print("Summary")
    print("=" * 70)

    print("\n📊 Generated Files:")
    files = [
        (f"01_original{ext}", "Original AI-generated audio"),
        (f"02_watermarked_metadata{ext}", "Metadata watermark (fast, lossless)"),
        ("03_evidence.json", "Forensic evidence record"),
        (f"04_stripped_metadata{ext}", "Tampered version (metadata removed)"),
    ]

    if os.path.exists(os.path.join(output_dir, f"05_watermarked_spectral{ext}")):
        files.append(
            (f"05_watermarked_spectral{ext}", "Spectral watermark (inaudible, re-encode resistant)")
        )

    for filename, description in files:
        path = os.path.join(output_dir, filename)
        if os.path.exists(path):
            size_kb = os.path.getsize(path) / 1024
            print(f"   ✅ {filename:35s} - {description} ({size_kb:.2f} KB)")

    print("\n💡 Watermarking Methods Comparison:")
    print("   • Metadata: Fast, lossless, but removable via re-encoding")
    print("   • Spectral: Slower, imperceptible, survives re-encoding and format conversion")
    print("   • Hybrid: Best of both - metadata + spectral embedding")

    print("\n🎯 Production Recommendations:")
    print("   1. Use metadata watermarking for internal tracking (fast)")
    print("   2. Use spectral watermarking for public distribution (tamper-resistant)")
    print("   3. Use hybrid mode for maximum protection")
    print("   4. Store evidence records with MFCC fingerprints for robust verification")
    print("   5. Implement verification API for audio authenticity checking")

    print("\n📚 Related Examples:")
    print("   - 01_basic_text_watermarking.py - Text watermarking")
    print("   - 06_image_watermarking.py - Image watermarking")
    print("   - 07_video_watermarking.py - Video watermarking")
    print("   - 05_verification.py - Verification workflows")

    print(f"\n✅ Example complete! Check output directory: {output_dir}/")


if __name__ == "__main__":
    main()
