"""
CIAF Watermarking - Video Metadata Watermarking

Inject watermark metadata into video containers without re-encoding.
Uses ffmpeg to modify container metadata while preserving video quality.

Created: 2026-04-05
Author: Denzil James Greenwood
Version: 1.0.0
"""

from typing import Optional, Dict, Any
import tempfile
import os


def _parse_frame_rate(rate: str) -> float:
    try:
        num_str, den_str = rate.split("/", 1)
        num = int(num_str)
        den = int(den_str)
        return num / den if den else 0.0
    except Exception:
        return 0.0


def apply_video_metadata_watermark(
    video_bytes: bytes,
    watermark_id: str,
    verification_url: str,
    model_id: str,
    timestamp: str,
    metadata: Optional[Dict[str, str]] = None,
) -> bytes:
    """
    Apply metadata watermark to video container.

    Uses ffmpeg to inject metadata without re-encoding, preserving quality.

    Args:
        video_bytes: Original video data
        watermark_id: Unique watermark identifier
        verification_url: URL for verification
        model_id: AI model identifier
        timestamp: Creation timestamp (ISO 8601)
        metadata: Additional metadata to include

    Returns:
        Watermarked video bytes (same quality as original)

    Raises:
        ImportError: If ffmpeg-python not installed
        RuntimeError: If ffmpeg processing fails

    Example:
        >>> from ciaf.watermarks.video import apply_video_metadata_watermark
        >>>
        >>> with open("video.mp4", "rb") as f:
        ...     video_bytes = f.read()
        >>>
        >>> watermarked = apply_video_metadata_watermark(
        ...     video_bytes=video_bytes,
        ...     watermark_id="wmk-abc123",
        ...     verification_url="https://vault.example.com/verify/wmk-abc123",
        ...     model_id="sora-v1",
        ...     timestamp="2026-04-05T10:30:00Z",
        ... )
        >>>
        >>> with open("watermarked.mp4", "wb") as f:
        ...     f.write(watermarked)
    """
    try:
        import ffmpeg
    except ImportError:
        raise ImportError(
            "Video metadata watermarking requires ffmpeg-python. "
            "Install with: pip install ffmpeg-python"
        )

    # Create temporary files
    with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as tmp_input:
        tmp_input.write(video_bytes)
        input_path = tmp_input.name

    output_path = input_path.replace(".mp4", "_watermarked.mp4")

    try:
        # Build metadata dictionary
        meta_dict = {
            "watermark_id": watermark_id,
            "verification_url": verification_url,
            "model_id": model_id,
            "timestamp": timestamp,
            "ciaf_watermark": "true",
        }

        # Add custom metadata if provided
        if metadata:
            meta_dict.update(metadata)

        # Build ffmpeg metadata arguments
        # Use -codec copy to avoid re-encoding (preserves quality)
        metadata_args = {}
        for key, value in meta_dict.items():
            metadata_args[f"metadata:{key}"] = str(value)

        # Also set standard metadata fields
        metadata_args["metadata:title"] = f"AI Generated - {model_id}"
        metadata_args["metadata:comment"] = (
            f"Watermark ID: {watermark_id} | Verify: {verification_url}"
        )
        metadata_args["metadata:description"] = f"Generated by {model_id} at {timestamp}"

        # Run ffmpeg with metadata injection (no re-encoding)
        (
            ffmpeg.input(input_path)
            .output(
                output_path,
                **{"c": "copy"},  # Copy codec - no re-encoding!
                **metadata_args,
            )
            .overwrite_output()
            .run(capture_stdout=True, capture_stderr=True, quiet=True)
        )

        # Read watermarked video
        with open(output_path, "rb") as f:
            watermarked_bytes = f.read()

        return watermarked_bytes

    except ffmpeg.Error as e:
        stderr = e.stderr.decode("utf-8") if e.stderr else "Unknown error"
        raise RuntimeError(f"ffmpeg metadata injection failed: {stderr}")

    finally:
        # Cleanup temporary files
        if os.path.exists(input_path):
            os.remove(input_path)
        if os.path.exists(output_path):
            os.remove(output_path)


def extract_video_metadata_watermark(video_bytes: bytes) -> Optional[Dict[str, str]]:
    """
    Extract watermark metadata from video container.

    Args:
        video_bytes: Potentially watermarked video

    Returns:
        Dictionary of watermark metadata if found, None otherwise

    Example:
        >>> watermark = extract_video_metadata_watermark(video_bytes)
        >>> if watermark:
        ...     print(f"Watermark ID: {watermark['watermark_id']}")
        ...     print(f"Model: {watermark['model_id']}")
        ...     print(f"Verification URL: {watermark['verification_url']}")
    """
    try:
        import ffmpeg
    except ImportError:
        # Can't extract without ffmpeg
        return None

    # Write to temporary file
    with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as tmp_file:
        tmp_file.write(video_bytes)
        tmp_path = tmp_file.name

    try:
        # Probe video metadata
        probe = ffmpeg.probe(tmp_path)

        # Check format-level metadata
        format_meta = probe.get("format", {}).get("tags", {})

        # Look for CIAF watermark marker
        if "ciaf_watermark" in format_meta or "watermark_id" in format_meta:
            # Extract watermark fields
            watermark_data = {}

            # Standard watermark fields
            watermark_fields = [
                "watermark_id",
                "verification_url",
                "model_id",
                "timestamp",
                "ciaf_watermark",
            ]

            for field in watermark_fields:
                if field in format_meta:
                    watermark_data[field] = format_meta[field]

            # Add any other custom fields
            for key, value in format_meta.items():
                if key not in watermark_data:
                    watermark_data[key] = value

            return watermark_data if watermark_data else None

        return None

    except Exception:
        # If probing fails, no watermark
        return None

    finally:
        # Cleanup
        if os.path.exists(tmp_path):
            os.remove(tmp_path)


def has_video_watermark(video_bytes: bytes) -> bool:
    """
    Check if video has CIAF watermark metadata.

    Args:
        video_bytes: Video data to check

    Returns:
        True if watermark detected, False otherwise

    Example:
        >>> if has_video_watermark(video_bytes):
        ...     print("Video is watermarked")
        ... else:
        ...     print("Video is not watermarked")
    """
    watermark = extract_video_metadata_watermark(video_bytes)
    return watermark is not None


def get_video_info(video_bytes: bytes) -> Dict[str, Any]:
    """
    Get video information using ffmpeg probe.

    Args:
        video_bytes: Video data

    Returns:
        Dictionary with video information (duration, codec, resolution, etc.)

    Example:
        >>> info = get_video_info(video_bytes)
        >>> print(f"Duration: {info['duration']:.1f} seconds")
        >>> print(f"Resolution: {info['width']}x{info['height']}")
        >>> print(f"Codec: {info['codec']}")
    """
    try:
        import ffmpeg
    except ImportError:
        raise ImportError(
            "Video info requires ffmpeg-python. " "Install with: pip install ffmpeg-python"
        )

    with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as tmp_file:
        tmp_file.write(video_bytes)
        tmp_path = tmp_file.name

    try:
        probe = ffmpeg.probe(tmp_path)

        # Get video stream
        video_stream = next((s for s in probe["streams"] if s["codec_type"] == "video"), None)

        if not video_stream:
            raise ValueError("No video stream found in file")

        # Extract info
        info = {
            "duration": float(probe["format"].get("duration", 0)),
            "size_bytes": int(probe["format"].get("size", 0)),
            "bitrate": int(probe["format"].get("bit_rate", 0)),
            "format": probe["format"].get("format_name", "unknown"),
            "codec": video_stream.get("codec_name", "unknown"),
            "width": int(video_stream.get("width", 0)),
            "height": int(video_stream.get("height", 0)),
            "fps": _parse_frame_rate(video_stream.get("r_frame_rate", "0/1")),
            "num_frames": int(video_stream.get("nb_frames", 0)),
        }

        return info

    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)
